# Tomas de Castro

CC=gcc
FLAGS=-Wall -Werror -Wextra -pedantic

hnm: 0_main.c
	$(CC) 0_main.c -o hnm
	cp hnm tests
	touch 0_main.c

hobjdump: 1_main.c
	$(CC) 1_main.c -o hobjdump
	cp hobjdump tests
	touch 1_main.c
