# Tomas de Castro

CC=gcc
FLAGS=-Wall -Werror -Wextra -pedantic

hnm: 0-main.c
	$(CC) $(FLAGS) 0-main.c -o hnm
	cp hnm tests
	touch 0-main.c

hobjdump: 1-main.c
	$(CC) $(FLAGS) 1-main.c -o hobjdump
	cp hobjdump tests
	touch 1-main.c
