CC=gcc
FLAGS=-Wall -Werror -Wextra -pedantic

0-hreadelf: 0-main.c
	$(CC) $(FLAGS) 0-main.c -o 0-hreadelf

1-hreadelf: 1-main.c
	$(CC) $(FLAGS) 1-main.c -o 1-hreadelf

2-hreadelf: 2-main.c
	$(CC) $(FLAGS) 2-main.c -o 2-hreadelf
